### ISSUE TITLE
incompatibility with Improved Anvils

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [Phoupraw/InfiniteFluidBucket#5]
Improved Anvils rejects the infinity enchantment on all items added in this mod.
My guess would be because of this line here <https://gitlab.com/davidjmacdonald1/improved-anvils/-/blob/main/src/main/java/com/davidjmacdonald/improved_anvils/mixin/AnvilScreenHandlerMixin.java?ref_type=heads#L259>.

**Comment by Phoupraw** [comment]
I am using no more than Fabirc API (`EnchantmentEvents.ALLOW_ENCHANTING`). Any fabric mod should keep compability with Fabric API. Please report to Improved Anvils. They should call `FabricItemStack.canBeEnchantedWith` instead, rather than directly call `Enchantment.isAcceptableItem`.
